### ISSUE TITLE
Notes on first usage

### ISSUE THREAD

**Issue by yelizariev** [xoe-labs/dockery-odoo#17]
This comment will be updated

- [x] The script doesn't check that docker-compose is installed, which doesn't allow us just *sit back and relax* :joy: 

- [ ] It's not obvious that 80 port must be free on running ``docker run``. No way to relax again :disappointed: :joy:

**Comment by blaggacao** [comment]
@yelizariev Can this be closed, too?

**Comment by yelizariev** [comment]
Not sure that did I mean on 80 port, but seems ok for me now
