### ISSUE TITLE
longpolling not working

### ISSUE THREAD

**Issue by shepilov-vladislav** [xoe-labs/dockery-odoo#24]
longpolling not working on latest version of scaffold repo :( 

<img width="384" alt="Screen Shot 2019-09-06 at 4 10 10 PM" src="https://user-images.githubusercontent.com/15679834/64430366-d5285800-d0c0-11e9-948f-16410d1fa0aa.png">

**Comment by blaggacao** [comment]
As a quick workaround, you could put the Odoo service into the public network and accessing it "traditionally" through `localhost` (without subdomain).

Maybe some other services need be put in the public network as well.

**Comment by blaggacao** [comment]
This is fixed, isn't it? @shepilov-vladislav
