### ISSUE TITLE
Edge 12.0: Patches not applying in CI/CD

### ISSUE THREAD

**Issue by theangryangel** [xoe-labs/dockery-odoo#26]
Not sure if this is me being dumb...

Using edge building the docker containers and applying the patches is fine in development.
Doing it in CI/CD results in none of the default dockery patches being applied.

I think the cause is that the Dockerfile renames the vendor directories to include LAYER_SUFFIX, but `/patches` is not aware of this and it fails. It works fine in dev because the directories are volume mounted into /opt/odoo/vendor.

I think I can see possible fixes, but I'm not sure which to send as pull request;
1. Remove all the layer suffix from the Dockerfile - but I don't understand it's purpose so I'm very reluctant to do that
2. Modify `/patches` to make it more aware of the LAYER_SUFFIX somehow?
3. Apply the patches in CI/CD before the image gets built (so modify .gitlab-ci.setup.yml in scaffold somehow)?
4. The patches are supposed to be committed to version control? Although that doesnt seem to make sense to me?

**Comment by blaggacao** [comment]
I guess this is finally fixed. It was more intricate as at first sight. Could you confirm? / Test? @theangryangel

**Comment by theangryangel** [comment]
Sorry haven’t gotten around to doing this yet. Still deep on “that” project and still have the workaround in place on the other one. I’ll come back to you if it doesn’t disappear when I got get around to removing it. Sorry for leaving you hanging :[

**Comment by blaggacao** [comment]
I guess I found it some time ago, and definitly fixed it.
Ours is working again. :+1:
