### ISSUE TITLE
Patches contains :: in filename causing it to be troublesome to clone on windows

### ISSUE THREAD

**Issue by ZerNox** [xoe-labs/dockery-odoo#4]
Hi! 
Got interested in your work and wanted to try it out. 
It was a bit halted by the patches.d filename convention on windows, is there maybe a possibility to change the filenames? 

[(https://github.com/xoe-labs/dockery-odoo/blob/master/images/base/v10/patches.d/odoo/0001-netsvc::Add-json-logging-when-not-tty-allowing-for-easier-log-aggregation.patch)]

Have a nice day!

**Comment by blaggacao** [comment]
@ZerNox the patches naming was planned to be regex-ed by to extract metadata, a"_" would be windows compliant and could do the same thing.

I'll refactor shortly.

About windows + docker: docker does not support file change notifications on windows, so during development autoreload wouldn't work.

This was so anyone to me at some point that I switched entirely to Linux. But if you're fine with manually restarting your docker during development, windows is fine, too for this approach.

**Comment by ZerNox** [comment]
That was fast, have a nice day!
