### ISSUE TITLE
headless browser for ci-image

### ISSUE THREAD

**Issue by yelizariev** [xoe-labs/dockery-odoo#7]
What is the way to get headless browser without installing x-server?

https://github.com/odoo/odoo/blob/12.0/odoo/tests/common.py#L497-L519

**Comment by yelizariev** [comment]
https://github.com/odoo/odoo/pull/26456

**Comment by blaggacao** [comment]
https://github.com/xoe-labs/dockery-odoo/blob/master/images/devops/Dockerfile the philosophy is to test on the contained image. There is a few seconds overhead in building it but you get reproducible environment and just can replicate the tests locally without any further plumbing.

**Comment by blaggacao** [comment]
What do you mean by "not optimal"?

**Comment by yelizariev** [comment]
I mean that we don't need X server to run headless browser. Am I wrong?

**Comment by blaggacao** [comment]
Does chrome headless use X server? I'm not sure if I understand the context right, I never came across that X server in this regard.

**Comment by yelizariev** [comment]
It should not use X server in theory, but it seems that Chrome itself doesn't support headless-only installation.
